import { Card } from "features/shared/types/card";

export const mockCards: Card [] = [
{
    id: 1,
    section: 'sneakers',
    pagination: 'Лучшая цена',
    name: 'Nike Defy All Day',
    coverImage: './images/Nike_Defy_All_Day_black.png',
    image_1: '',
    fullPrice: 12990,
    currency: 32,
    salePrice: 9000,
  },
  {
    id: 2,
    section: 'sneakers',
    pagination: 'Хит сезона',
    name: 'Nike Varsity Royal',
    coverImage: './Nike_Varsity_Royal_blue.png',
    image_1: '',
    fullPrice: 22990,
    currency: 17,
    salePrice: 12000,
  },
  {
    id: 3,
    section: 'sneakers',
    pagination: 'Топ продаж',
    name: 'Nike Air Max TW SE',
    coverImage: './Nike_Air_Max_TW_SE_white.png',
    image_1: '',
    fullPrice: 12990,
    currency: 12,
    salePrice: 10000,
  },
  {
    id: 4,
    section: 'sneakers',
    pagination: '',
    name: 'Nike Dunk High Retro Premium',
    coverImage: 'Nike_Defy_All_Day_black.png',
    image_1: '',
    fullPrice: 12990,
    currency: 12,
    salePrice: 10000,
  },
  {
    id: 5,
    section: 'sneakers',
    pagination: 'Лучшая цена',
    name: 'Nike Dunk High Retro Premium',
    coverImage: 'Nike_Defy_All_Day_black.png',
    image_1: '',
    fullPrice: 12990,
    currency: 12,
    salePrice: 10000,
  },
  {
    id: 6,
    section: 'sneakers',
    pagination: 'Хит сезона',
    name: 'Nike Dunk High Retro Premium',
    coverImage: 'Nike_Defy_All_Day_black.png',
    image_1: '',
    fullPrice: 12990,
    currency: 12,
    salePrice: 10000,
  },
];